# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31eddcbcb54d978ec221ec0b80baba6ed041a20b48a093b2fcf1ca721e65bc85e2f8c8c1f66e8e77c9fb7bd09224765efdc0a16baab58ebc69e1d21f615a70f1

test:
  secret_key_base: be6f27d83418bd9da46f0508a781ba765f0b97fb98ddfd386cf62a9e9d6347a2aa6feaa352fd326c172fe900b6734c1a29b01284c8795c9125d64c1fb0e5ced5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e2c3edf724cc87ee2e0bdf1ea06ce238708d560ba8a1ff29b0be5a12af7c6ee0963dfa583c0920fa01f7a3a0ec2b015b61ae63371b51adf20a549d19671582b5
